server:
  port: 9006
  servlet:
    context-path: /api
  compression:
    enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  http:
    encoding:
      charset:utf-8
      force:true
      enabled:true
#  dubbo:
#    registry: zookeeper://localhost:2181
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: product

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181

#management.endpoints.web.exposure.include: '*'
#management.endpoint.health.show-details: always
#
#management.health.diskspace.enabled: false
#management.health.circuitbreakers.enabled: true
#management.health.ratelimiters.enabled: false
#
#management.metrics.tags.application: ${spring.application.name}
#management.metrics.distribution.percentiles-histogram.http.server.requests: true
#management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 5
  instances:
    bulkhead:
      maxConcurrentCalls: 5
      maxWaitDuration: 5s
    testConcurrentCalls:
      maxConcurrentCalls: 5
      maxWaitDuration: 5s
    testMaxWaitDuration:
      # 假设我们希望将并发调用的数量限制为 500，并且我们愿意等待 2 秒让线程获得许可：
      maxConcurrentCalls: 500
      maxWaitDuration: 2s

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
  instances:
    externalConcurrentService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      writableStackTraceEnabled: true

resilience4j.circuitbreaker:
  instances:
    externalConcurrentService:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 500ms
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 10s
      recordExceptions:
        - com.demo.product.exception.CircuitBreakerException
    externalConcurrentService2:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 500ms
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 10s
      recordExceptions:
        - com.demo.product.exception.CircuitBreakerException