server:
  port: 9005
  servlet:
    context-path: /api
  compression:
    enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  http:
    encoding:
      charset:utf-8
      force:true
      enabled:true
#  dubbo:
#    server: true
#    registry: zookeeper://localhost:2181
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: user

# Dubbo 应用名称
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181

