## 正常
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 127.0.0.1:5000/product:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9006
          env:
            - name: TZ
              value: Asia/Shanghai
---

## 直接部署到集群外
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-nodeport
spec:
  type: NodePort
  ports:
    - port: 9006
      protocol: TCP
      nodePort: 32006
  selector:
    app: product

